tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-primary-fixed-variant": "#004c6b",
              "tertiary": "#8d4f00",
              "surface-container-highest": "#e0e3e5",
              "primary-fixed": "#c6e7ff",
              "inverse-primary": "#82cfff",
              "secondary": "#4c616c",
              "secondary-container": "#cfe6f2",
              "on-tertiary-fixed": "#2d1600",
              "primary-container": "#00aeef",
              "on-primary-container": "#003e58",
              "surface": "#f7f9fb",
              "on-error": "#ffffff",
              "inverse-surface": "#2d3133",
              "surface-bright": "#f7f9fb",
              "on-secondary-fixed": "#071e27",
              "on-tertiary-container": "#572f00",
              "surface-variant": "#e0e3e5",
              "tertiary-fixed": "#ffdcc0",
              "surface-container-lowest": "#ffffff",
              "on-tertiary": "#ffffff",
              "surface-container": "#eceef0",
              "on-primary": "#ffffff",
              "outline-variant": "#bdc8d1",
              "secondary-fixed-dim": "#b4cad6",
              "on-error-container": "#93000a",
              "secondary-fixed": "#cfe6f2",
              "on-secondary-fixed-variant": "#354a53",
              "tertiary-fixed-dim": "#ffb876",
              "on-tertiary-fixed-variant": "#6b3b00",
              "on-secondary-container": "#526772",
              "error-container": "#ffdad6",
              "tertiary-container": "#ea8c21",
              "surface-tint": "#00658d",
              "error": "#ba1a1a",
              "background": "#f7f9fb",
              "on-secondary": "#ffffff",
              "on-surface": "#191c1e",
              "primary-fixed-dim": "#82cfff",
              "on-primary-fixed": "#001e2d",
              "primary": "#00658d",
              "surface-dim": "#d8dadc",
              "on-background": "#191c1e",
              "inverse-on-surface": "#eff1f3",
              "surface-container-low": "#f2f4f6",
              "surface-container-high": "#e6e8ea",
              "outline": "#6e7881",
              "on-surface-variant": "#3e4850"
            },
            fontFamily: {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
          },
        },
      }